#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

UUID='51baf9b5-0288-40cf-bf21-af80ef80be23'

cryptsetup luksOpen /dev/disk/by-uuid/$UUID llave

if [ -h /dev/mapper/llave ]
then
  mkdir -p /mnt/llave
  mount /dev/mapper/llave /mnt/llave
fi

if [ -d /mnt/llave ]
then
  cd $HOME
  mkdir -p .config
  ln -s /mnt/llave/.gnupg
  ln -s /mnt/llave/.imapfilter
  ln -s /mnt/llave/.password-store
  ln -s /mnt/llave/.password-store-gcoop
  ln -s /mnt/llave/.ssh

  ln -s /mnt/llave/bin
  ln -s /mnt/llave/blog
  ln -s /mnt/llave/config
  ln -s /mnt/llave/direplos
  ln -s /mnt/llave/git-bash-utils
  ln -s /mnt/llave/hmtl
  ln -s /mnt/llave/media-bash-utils
  ln -s /mnt/llave/org
  ln -s /mnt/llave/org-bash-utils
  ln -s /mnt/llave/pcap2dot
  ln -s /mnt/llave/plan-b

  ln -s /mnt/llave/config/awesome .config/awesome
  ln -s /mnt/llave/config/bash/bash_aliases .bash_aliases
  ln -s /mnt/llave/config/bash/bash_profile .bash_profile
  ln -s /mnt/llave/config/bash/bashrc .bashrc
  ln -s /mnt/llave/config/conky/conkyrc .conkyrc
  ln -s /mnt/llave/config/git/git-repos .git-repos
  ln -s /mnt/llave/config/git/gitconfig .gitconfig
  ln -s /mnt/llave/config/links2 .links2
  ln -s /mnt/llave/config/mocp .moc
  ln -s /mnt/llave/config/mutt/mailcap .mailcap
  ln -s /mnt/llave/config/offlineimap/offlineimaprc .offlineimaprc
  ln -s /mnt/llave/config/ssh/config .ssh/config
  ln -s /mnt/llave/config/terminator .config/terminator
  ln -s /mnt/llave/config/tmux/tmux.conf .tmux.conf
  ln -s /mnt/llave/config/vimperator/vimperatorrc .vimperatorrc
  ln -s /mnt/llave/config/vim .vim
  ln -s /mnt/llave/config/vim/vimrc .vimrc
  ln -s /mnt/llave/config/x/xinitrc .xinitrc
  ln -s /mnt/llave/config/x/xmodmaprc .xmodmaprc
fi

